### ISSUE TITLE
#9 Divs

### ISSUE THREAD

**Issue by ReneKrewinkel** [MaaikeBommerson/educom-html#9]
<p>Volg het onderdeel "Divs" en maak de opdracht.</p>
<p><a href="https://e-learning.educom.nu/essentials/HTML/divs">https://e-learning.educom.nu/essentials/HTML/divs</a></p>

**Comment by MaaikeBommerson** [comment]
Tenzij het gaat om de twee images in 1 div tag te zetten, in dat geval komen ze naast elkaar te staan ipv onder elkaar
